### Creating Numpy Array 

In [1]:
import numpy as np
arr = np.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [2]:
# 2D and 3D array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
# 3D array
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [4]:
# dtype
arr = np.array([1,2,3],dtype = float)
print(arr)

[1. 2. 3.]


In [5]:
# arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# with reshape 
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
# np.ones and np.zeros with tuple dtype float by default
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros((2,4),dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [9]:
# np.random
np.random.random((2,4))

array([[0.95538401, 0.54903541, 0.70047875, 0.41065351],
       [0.48284147, 0.23948717, 0.58227278, 0.11326075]])

In [10]:
# np.linspace -----> linearly spaced
np.linspace(2,8,6)

array([2. , 3.2, 4.4, 5.6, 6.8, 8. ])

In [11]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Array Attributes

In [12]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [13]:
# ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [14]:
#shape
a2.shape

(3, 4)

In [15]:
#size
a2.size

12

In [16]:
# itemsize
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
4


In [17]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


In [18]:
#changing datatype
np.array([1,2,3,4,5])
arr.astype(np.int32)

array([1, 2, 3])

### Array operations

In [19]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
# scalar operations
# arithmetic operation with scalr
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [21]:
# scalar operations
# relational operation with scalar
a1 > 6
a1 ==5
a1 <=2

array([[ True,  True,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [22]:
# Vector operation arithmetic
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

## Array Functions

In [23]:
a1 = np.random.random((3,4))
a1 = np.round(a1*100)
print(a1)

[[41. 46. 45. 39.]
 [67. 50. 85. 33.]
 [16. 85. 65. 10.]]


In [24]:
# max/min/sum/prod
np.max(a1)
np.min(a1)
np.prod(a1)
np.sum(a1)

582.0

In [25]:
# axis 0 ----> column , axis 1 -----> row
np.max(a1,axis = 1)

array([46., 85., 85.])

In [26]:
np.min(a1,axis = 0)

array([16., 46., 45., 10.])

In [27]:
# mean/median/std/var
np.mean(a1,axis = 1)
np.median(a1,axis = 1)
np.std(a1,axis = 1)
np.var(a1,axis = 1)

array([   8.1875,  374.1875, 1015.5   ])

In [28]:
# Trignometric functions
np.sin(a1)
np.cos(a1)

array([[-0.98733928, -0.43217794,  0.52532199,  0.26664293],
       [-0.5177698 ,  0.96496603, -0.98437664, -0.01327675],
       [-0.95765948, -0.98437664, -0.56245385, -0.83907153]])

In [29]:
# dot product
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)
np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [30]:
# log and exponent
np.log(a2)
np.exp(a2)

array([[1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09]])

In [31]:
# round flour ceil
np.round(np.random.random((2,3)) * 100)

array([[43., 85., 30.],
       [79., 87., 43.]])

In [32]:
np.ceil(np.random.random((2,3))*100)


array([[ 6., 21., 14.],
       [38., 78., 41.]])

In [33]:
np.floor(np.random.random((2,3))*100)

array([[38., 96., 52.],
       [ 7., 71., 39.]])

In [34]:
in_array = [.5, 1.5, 2.5, 3.5, 4.5, 10.1] 
print ("Input array : \n", in_array) 
  
ceiloff_values = np.ceil(in_array) 
print ("\nRounded values : \n", ceiloff_values) 

Input array : 
 [0.5, 1.5, 2.5, 3.5, 4.5, 10.1]

Rounded values : 
 [ 1.  2.  3.  4.  5. 11.]


# Indexing 

In [35]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a4 = np.arange(16).reshape(2,2,2,2)
a5 = np.arange(32).reshape(2,2,2,2,2)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a1
a1[-1]

9

In [37]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
a2[1,2]

6

In [39]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [40]:
a3[1,0,1]

5

In [41]:
a3[0,1,0]

2

In [42]:
a3[0,0,0]

0

In [43]:
a4

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [44]:
a4[1,0,0,1]

9

In [45]:
a4[1,1,0,1]

13

In [46]:
a5

array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]],



       [[[[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]],


        [[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]]]])

In [47]:
 a5[1,1,1,1,1]

31

In [48]:
a5[1,1,0,0,0]

24

# slicing

In [49]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a1[2:5]

array([2, 3, 4])

In [51]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
a2[0,:]

array([0, 1, 2, 3])

In [53]:
a2[:,2]

array([ 2,  6, 10])

In [54]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [55]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [56]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [57]:
a2[1,::3]

array([4, 7])

In [58]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [61]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [83]:
a3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

# iterating

In [84]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [86]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [88]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [89]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [90]:
# nditer
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [91]:
# reshape

In [94]:
# transpose --------------- > rows convert to column and column convert to rows 
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [96]:
# revel converts n-D array into 1-D array
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Stacking

In [101]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [105]:
# horiontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [106]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Spliting

In [107]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
# horizontal spliting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [113]:
# vertical spliting
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]